#!/bin/bash
# Auto-generated by LIPE.HOST deploy executor
cd /var/www/lipehost/deploys/cmsv5tbq70001kpd9i733ha1p/.next/standalone
export PORT=3993
export NODE_ENV=production
export DATABASE_URL=file:/var/www/lipehost/deploys/cmsv5tbq70001kpd9i733ha1p/db/custom.db
export HOSTNAME=0.0.0.0
export NEXTAUTH_URL=https://dashboard.newmobility.com.br
export NEXTAUTH_SECRET=lh-cmsv5tbq7000-lh-salt-2026
export AUTH_TRUST_HOST=true
exec node server.js
