import { db, prisma } from '@/lib/db'
import { success, error } from '@/lib/api-utils'
import { isKycApproved } from '@/lib/kyc'

// Plan prices and ordering are no longer hardcoded — they are sourced
// from the `Plan` table (the single source of truth, editable by admins
// via /api/admin/plans). The `priceCents` and `sortOrder` columns on
// each Plan row drive both the invoice amount and the upgrade-direction
// validation below.
//
// ─── Blue 3 → Premium 5 upgrade flow (Índice.docx §3 + §1.1) ─────────
// `blue3`   entry fee R$150   → locks entrada at 3 levels (earn L1-L3)
// `premium5` upgrade R$850    → unlocks entrada levels 4-5 (earn L1-L5)
//
// The `premium5` plan code is an alias of the DB's `blue5` row — both
// describe the same R$850 upgrade tier. The client spec calls it
// "Premium 5" so we accept `toPlan: "premium5"` from the frontend and
// resolve it to the underlying `blue5` Plan row when validating the
// upgrade direction.
//
// Two payment methods are supported:
//   1. `automatic` — deducts R$850 immediately from the user-chosen
//      wallet (`walletSource: "withdrawal" | "paymentInvoice"`). The
//      upgrade is applied instantly, a paid Transaction is recorded,
//      and a Notification informs the user that levels 4-5 are unlocked.
//   2. `manual`    — creates a pending R$850 Invoice and a pending
//      Transaction. The user pays via PIX externally; payment is then
//      confirmed via /api/plans/confirm-pix (or a bank webhook in prod).
//
// Legacy `paymentMethod: "pix" | "balance"` values are still accepted
// for backward compatibility with the old myplan-page.tsx dialog flow.

const PREMIUM5_ALIASES = new Set(['premium5', 'blue5'])

// Map a `toPlan` code coming from the frontend to the canonical Plan
// code stored in the DB. `premium5` is an alias of `blue5` (same R$850
// upgrade tier; client spec calls it "Premium 5", DB stores it as blue5).
function resolveToPlanCode(toPlan: string): string {
  if (toPlan === 'premium5') return 'blue5'
  return toPlan
}

// Map a Plan DB code back to the client-spec display name.
function planDisplayName(code: string): string {
  if (code === 'blue5' || code === 'premium5') return 'Premium 5'
  if (code === 'blue3') return 'Blue 3'
  if (code === 'free') return 'Gratuito'
  return code
}

/**
 * Generate a mock PIX BR Code (BRcode) string.
 * This is the "copia e cola" code users can paste in their bank app.
 * Format follows the BR Code structure (simplified for demo).
 */
function generatePixBrCode(amountCents: number, description: string, txid: string): string {
  // PIX BR Code format - simplified mock following the EMV standard structure
  // In production, this would be generated by the bank's API
  const amount = (amountCents / 100).toFixed(2)
  const merchantName = 'NEWMOBILITY LTDA'
  const merchantCity = 'SAO PAULO'

  // Helper to build TLV fields
  const tlv = (id: string, value: string) => {
    const len = value.length.toString().padStart(2, '0')
    return `${id}${len}${value}`
  }

  // Build the BR Code (simplified mock - NOT a real valid PIX)
  const parts = [
    tlv('00', 'br.gov.bcb.pix'),                    // Payload format indicator
    tlv('01', '12'),                                 // Point of initiation method (12 = dynamic)
    // Merchant account info (sub-fields)
    tlv('26', tlv('00', 'br.gov.bcb.pix') + tlv('01', 'newmobility@pix.com.br') + tlv('02', txid)),
    tlv('52', '0000'),                               // Merchant category code
    tlv('53', '986'),                                // Transaction currency (BRL)
    tlv('54', amount),                               // Transaction amount
    tlv('58', 'BR'),                                 // Country code
    tlv('59', merchantName),                         // Merchant name
    tlv('60', merchantCity),                         // Merchant city
    tlv('62', tlv('05', txid) + tlv('50', tlv('00', 'BR.GOV.BCB.PIX') + tlv('01', description.substring(0, 50)))), // Additional data
  ]

  const payload = parts.join('')
  // CRC16/CCITT-FALSE calculation (simplified - for demo we use a fixed value)
  const crc = '6304' // In production this would be the actual CRC16
  return payload + crc
}

// Wallet column name on the User table for each `walletSource` accepted
// by the automatic flow. Mirrors the mapping in /api/financial/transfer.
const WALLET_FIELDS: Record<string, string> = {
  withdrawal: 'balanceWithdrawal',
  paymentInvoice: 'balancePaymentInvoice',
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    // Accept both the new (fromPlan/toPlan/paymentMethod/walletSource)
    // and legacy (plan/paymentMethod) request shapes.
    const userId = body.userId
    const toPlanRaw = body.toPlan || body.plan // accept alias
    const fromPlan = body.fromPlan || '' // optional, used for descriptive messages
    // paymentMethod values: 'automatic' | 'manual' | 'pix' (legacy) | 'balance' (legacy)
    const paymentMethod = body.paymentMethod || 'manual'
    const walletSource = body.walletSource // 'withdrawal' | 'paymentInvoice' (automatic only)

    if (!userId || !toPlanRaw) {
      return error('userId and toPlan (or plan) are required')
    }

    // Resolve alias premium5 -> blue5 for DB lookups
    const toPlanCode = resolveToPlanCode(toPlanRaw)

    // Look up the target plan from the DB (single source of truth for prices).
    // Only `isDefault: true` plans are valid upgrade targets — this excludes
    // monthly add-on plans (mensalidade_*) which are billed separately.
    const planRecord = await prisma.plan.findUnique({ where: { code: toPlanCode } })
    if (!planRecord || !planRecord.isActive || !planRecord.isDefault) {
      return error('Invalid plan. Plan not found, inactive, or not an upgrade target.')
    }
    const price = planRecord.priceCents
    const targetOrder = planRecord.sortOrder

    const user = await db.findOne('User', '"id" = $1', [userId])
    if (!user) {
      return error('User not found', 404)
    }

    // KYC gate: block plan upgrades if user's KYC is not approved (admins bypass).
    if (user.role !== 'admin' && user.userType !== 'admin' && user.userType !== 'ADMIN') {
      const kycOk = await isKycApproved(user.id as string)
      if (!kycOk) {
        return error(
          'KYC não aprovado. Complete sua verificação de documentos na aba KYC para evoluir de plano.',
          403
        )
      }
    }

    // Look up the user's current plan from the DB to determine upgrade
    // direction (replaces the hardcoded PLAN_ORDER map).
    let currentOrder = 0
    let currentPlanCode = user.plan || 'free'
    if (currentPlanCode === 'premium5') currentPlanCode = 'blue5' // normalize
    if (currentPlanCode && currentPlanCode !== 'free') {
      const currentPlanRecord = await prisma.plan.findUnique({ where: { code: currentPlanCode } })
      currentOrder = currentPlanRecord?.sortOrder ?? 0
    }

    // Check if it's actually an upgrade
    if (targetOrder <= currentOrder) {
      return error('Can only upgrade to a higher plan')
    }

    // Due date for the invoice (3 days from now)
    const dueDate = new Date()
    dueDate.setDate(dueDate.getDate() + 3)

    // Generate transaction ID for PIX
    const txid = `NM${Date.now()}${Math.random().toString(36).substring(2, 8).toUpperCase()}`.substring(0, 25)

    const targetDisplayName = planDisplayName(toPlanRaw)

    // ─── AUTOMATIC FLOW: deduct from chosen wallet, apply upgrade instantly
    if (paymentMethod === 'automatic') {
      if (!walletSource || !WALLET_FIELDS[walletSource]) {
        return error('walletSource is required for automatic payment (use "withdrawal" or "paymentInvoice")', 400)
      }
      const walletField = WALLET_FIELDS[walletSource]
      const currentBalance = (user as any)[walletField] || 0
      if (currentBalance < price) {
        return error(
          `Saldo insuficiente em ${walletSource === 'withdrawal' ? 'Saldo para Saque' : 'Saldo para Faturas'}. Disponível: ${currentBalance} cents, necessário: ${price} cents.`,
          400
        )
      }

      // Deduct from the chosen wallet, activate plan
      await db.update('User', '"id" = $1', {
        plan: toPlanCode,
        isActive: true,
        [walletField]: currentBalance - price,
      }, [userId])

      // Mark any existing pending R$150 / R$850 invoices for this user as paid
      // (per client spec §3: after upgrade, both invoices "disappear from
      // backoffice" — we mark them paid so the invoices list filters them out).
      const pendingInvoices = await db.find(
        'Invoice',
        '"userId" = $1 AND "status" = $2',
        [userId, 'pending']
      ) as any[]
      for (const inv of pendingInvoices) {
        if (inv.type === `plan_${toPlanCode}` || inv.type === `plan_premium5` || inv.type === `plan_blue3`) {
          await db.update('Invoice', '"id" = $1', {
            status: 'paid',
            paidAt: new Date(),
          }, [inv.id])
        }
      }

      // Create a paid invoice recording the upgrade payment (per spec §3)
      const invoice = await db.insert('Invoice', {
        userId,
        amount: price,
        type: `plan_${toPlanCode}`,
        status: 'paid',
        dueDate,
        paidAt: new Date(),
      })

      // Transaction record (negative = money out, status paid)
      const txCategory = walletSource === 'paymentInvoice' ? 'paymentInvoice' : 'gratification'
      await db.insert('Transaction', {
        userId,
        type: 'upgrade',
        amount: -price,
        status: 'paid',
        category: txCategory,
        description: `Upgrade ${planDisplayName(currentPlanCode)} → ${targetDisplayName} (R$ ${(price / 100).toFixed(2).replace('.', ',')} — descontado de ${walletSource === 'withdrawal' ? 'Saldo para Saque' : 'Saldo para Faturas'})`,
      })

      // Notification: inform user of successful upgrade + unlocked levels
      await db.insert('Notification', {
        userId,
        title: `Upgrade para ${targetDisplayName} realizado!`,
        message: `Seu plano foi atualizado para ${targetDisplayName}. Os níveis 4 e 5 da matriz Entrada foram desbloqueados — agora você pode receber comissões dos níveis 1 a 5.`,
        type: 'plan_upgrade',
      })

      const updatedUser = await db.findOne('User', '"id" = $1', [userId])
      return success({
        invoice,
        user: updatedUser,
        plan: toPlanCode,
        planAlias: toPlanRaw,
        paid: true,
        paymentMethod: 'automatic',
        walletSource,
        unlockedLevels: 5,
        message: `Upgrade para ${targetDisplayName} realizado com sucesso. Níveis 4 e 5 da matriz Entrada desbloqueados.`,
      }, 201)
    }

    // ─── MANUAL FLOW: generate a pending invoice + PIX code (user pays externally)
    // Also accepts the legacy `paymentMethod: "pix"` value as an alias for "manual".
    if (paymentMethod === 'manual' || paymentMethod === 'pix') {
      // Check if there's already a pending invoice for this plan/user
      const existingPending = await db.find(
        'Invoice',
        '"userId" = $1 AND "status" = $2 AND "type" = $3',
        [userId, 'pending', `plan_${toPlanCode}`]
      )

      let invoice: any
      if (existingPending && existingPending.length > 0) {
        // Reuse the existing pending invoice
        invoice = existingPending[0]
      } else {
        // Create new pending invoice
        invoice = await db.insert('Invoice', {
          userId,
          amount: price,
          type: `plan_${toPlanCode}`,
          status: 'pending',
          dueDate,
        })
      }

      // Generate PIX BR Code — use the DB-sourced plan name so admin
      // renames propagate to invoice descriptions and PIX payloads.
      const planName = `Plano ${targetDisplayName}`
      const pixCode = generatePixBrCode(price, `${planName} - NewMobility`, txid)

      // Create a pending transaction record for the upgrade attempt
      // (not yet applied - will be approved when PIX is paid)
      await db.insert('Transaction', {
        userId,
        type: 'upgrade',
        amount: price,
        status: 'pending',
        category: 'plan_upgrade',
        description: `Aguardando pagamento PIX - Upgrade para ${planName} (TXID: ${txid})`,
      })

      return success({
        invoice,
        pixCode,
        pixTxid: txid,
        amount: price,
        planName,
        planAlias: toPlanRaw,
        plan: toPlanCode,
        expiresAt: dueDate.toISOString(),
        instructions: [
          'Abra o aplicativo do seu banco',
          'Escolha a opção PIX -> Pagar com QR Code ou Copia e Cola',
          'Escaneie o QR Code ou cole o código PIX',
          'Confirme o pagamento',
          'Após o pagamento, seu plano será ativado em até 5 minutos',
        ],
        // For demo: provide a "simulate payment" link
        simulatePayment: true,
      }, 201)
    }

    // ─── LEGACY balance flow (kept for backward compat with old dialog)
    if (paymentMethod === 'balance') {
      // Check if user has sufficient free balance
      if ((user.balanceFree || 0) < price) {
        return error('Saldo insuficiente para upgrade', 400)
      }
      // Deduct from balance and apply upgrade immediately
      await db.update('User', '"id" = $1', {
        plan: toPlanCode,
        isActive: true,
        balanceFree: (user.balanceFree || 0) - price,
      }, [userId])

      const invoice = await db.insert('Invoice', {
        userId,
        amount: price,
        type: `plan_${toPlanCode}`,
        status: 'paid',
        dueDate,
        paidAt: new Date(),
      })

      await db.insert('Transaction', {
        userId,
        type: 'withdrawal',
        amount: -price,
        status: 'approved',
        category: 'plan_upgrade',
        description: `Upgrade para ${targetDisplayName} (pago com saldo)`,
      })

      const updatedUser = await db.findOne('User', '"id" = $1', [userId])
      return success({ invoice, user: updatedUser, plan: toPlanCode, paid: true }, 201)
    }

    return error('Método de pagamento não suportado. Use "automatic", "manual" ou "balance".', 400)
  } catch (err) {
    console.error('Plan upgrade error:', err)
    return error('Internal server error', 500)
  }
}
